### ISSUE TITLE
/enter & garages dont work

### ISSUE THREAD

**Issue by Dankbudbaker** [qbcore-framework/qb-houses#10]
so downloading latest verison. after creating a house then buying the house the /enter doesnt show up nor works. you can create a garage but it doesnt show up nor works.

**Comment by Dankbudbaker** [comment]
if i revert the changed shown here https://github.com/qbcore-framework/qb-houses/commit/6007a0a2aa849f0bbebc48adfde26713599a24ab 

it fixes my issue.

**Comment by ianvalls90** [comment]
I can confirm this issue, no /enter sign anymore on house doors.

**Comment by G4Tommo** [comment]
If you "fly" into your house from spawn also, no exit and need to relog

**Comment by GhzGarage** [comment]
Just tested with a fresh build


![20210720205210_1](https://user-images.githubusercontent.com/57848836/126418104-a498e388-c54b-4ad2-9189-568b2a21834b.jpg)
