### ISSUE TITLE
[BUG] Floating stuff.

### ISSUE THREAD

**Issue by BlueSky-fur** [qbcore-framework/qb-houses#102]
**Describe the bug**
Some Sofas, tables, and props in general float even tho we place then on the ground either with ALT or manually. also some props have npcs sitting on them after a server restart.

**To Reproduce**
1. Buy a Sofa or some specific tables
2. place them on the ground
3. exit the decorate menu

**Expected behavior**
I was expecting the props not to float and having no random npcs in my house 

**Screenshots**
https://gyazo.com/ebdf69d3902b28329b770fd7e9b4f718

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] Yesterday.
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] a few but nothing that impacts props in any sort of way.
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no.

**Additional context**

**Comment by PlanovskyJus** [comment]
Was there ever a fix for this? I am having this issue currently.
