### ISSUE TITLE
[BUG] Props starting with `v_` will not load / spawn

### ISSUE THREAD

**Issue by ihyajb** [qbcore-framework/qb-houses#105]
**Describe the bug**
**[Props starting in `v_` will not spawn]**

**To Reproduce**
1. Start your server
2. Load into Sandy
3. Try to spawn prop such as `v_res_tre_sofa` (prop shouldnt spawn)
4. Go to `vector3(-1154.7, -1518.32, 10.63)`
5. Try and spawn the prop again (prop should spawn)

**Expected behavior**
Props starting in `v_ `are part of an mlo's / IPL's and can only spawned near them. Or if you load the ytype or have them in your memory (aka going close to them). You cannot use `RequestModel` to request those props. Ive attached my code below on how I tested this. I also got help from the mods in the "Pleb Master" discord to help me confirm this.

**Code I used to test:**
```lua
RegisterCommand('proptest', function()
	model = `v_res_tre_sofa_mess_a`
    RequestModel(model)
    while not HasModelLoaded(model) do
        Wait(1)
		print(HasModelLoaded(model))
    end
    ugh = CreateObject(model, GetEntityCoords(PlayerPedId()), true, true, false)
	Wait(3000)
	DeleteObject(ugh)
	print(ugh)
end)
```

**Questions (please complete the following information):**
 - When you last updated: **[Just updated to test this bug]**
 - Are you using custom resource? which ones? **[N/A. Installed a Fresh Build]**
 - Have you renamed `qb-` to something custom? **[N/A]**

**Additional context**
**[Theres over 350+ props in the config that will not work due to not having the object loaded into memory]**

**Comment by ihyajb** [comment]
updated with more info

**Comment by complexza** [comment]
@ihyajb Sorry for the tag, But do you know a fix for this at all or should those props be yeeted from the config?
