### ISSUE TITLE
[BUG] buy same house multiple time 

### ISSUE THREAD

**Issue by GeekHamza1** [qbcore-framework/qb-houses#109]
after realestate sell house to a player , other player can come to that location and buy house again  in the same location

**Comment by RadhwaneDZ** [comment]
i confirm that fresh deploy and same issue if realestate create a house and a player buy it he can enter to his house 
but if other play come to that house location he will see " view house " and he can pay for the house and can own it if the 2 players enter the house they see each other inside house

**Comment by jay-fivem** [comment]
Fixed in #118

**Comment by GhzGarage** [comment]
Fix pushed
