### ISSUE TITLE
[BUG] decoration issue 

### ISSUE THREAD

**Issue by RadhwaneDZ** [qbcore-framework/qb-houses#112]
some buttons not working like ESC  and LEFTALT
also when trying to purchase props you can buy it but you cant place it 

![This is an image](https://cdn.discordapp.com/attachments/831653036148654101/927394914029944832/unknown.png)

**Comment by Mojito-Fivem** [comment]
Can't reproduce, try updating the resource

**Comment by RadhwaneDZ** [comment]
after update here is another issue 
```lua
[    script:qb-houses] SCRIPT ERROR: @qb-houses/server/main.lua:359: attempt to compare nil with number
[    script:qb-houses] > TriggerCallback (@qb-core/server/functions.lua:205)
[    script:qb-houses] > handler (@qb-core/server/events.lua:119)
[      script:qb-core] SCRIPT ERROR: error object is not a string
[      script:qb-core] (nil stack trace)
```

**Comment by Mojito-Fivem** [comment]
Running on an updated qb build and had no issues with it
