### ISSUE TITLE
[SUGGESTION] QB-Houses remove house? 

### ISSUE THREAD

**Issue by ShaAlexander** [qbcore-framework/qb-houses#122]
I would love to see a function to delete any old players houses or just every house like /createhouse for the realestate /removehouse.

**Comment by GeekHamza1** [comment]
delete it in mysql

**Comment by ShaAlexander** [comment]
That’s to much hassle and did you even read my post. The real estate people cannot log in to the db.

**Comment by AnassaHecate** [comment]
> That’s to much hassle and did you even read my post. The real estate people cannot log in to the db.
> […](#)
> Op 11 jan. 2022 om 21:57 heeft GeekHamza1 ***@***.***> het volgende geschreven: ﻿ delete it in mysql — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.

I would love this command especially since I am very new to all this. Where do I find the file where player houses get stored?

**Comment by GeekHamza1** [comment]
> > That’s to much hassle and did you even read my post. The real estate people cannot log in to the db.
> > […](#)
> > Op 11 jan. 2022 om 21:57 heeft GeekHamza1 _**@**_.***> het volgende geschreven: ﻿ delete it in mysql — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.
> 
> I would love this command especially since I am very new to all this. Where do I find the file where player houses get stored?

player house saved in database in MySQL  , table : player_houses and houselocations

**Comment by MonkeyWhisper** [comment]
I'll work on making a command for it.

**Comment by Duguayster** [comment]
Not only that, but allow the player to sell the house, and it just goes back on the market as well. And have the option for the realestate agent to remove the house with a command in case they messed up or just need to remove the property.

**Comment by MonkeyWhisper** [comment]
> Not only that, but allow the player to sell the house, and it just goes back on the market as well. And have the option for the realestate agent to remove the house with a command in case they messed up or just need to remove the property.

Allowing the players to sell the house and go back up for sale is not something that I will do. I'm very against that for a couple of reasons, but if another dev wants to code it... be my guest. 

I already said I was working on the command.

**Comment by oosayeroo** [comment]
hi. Im also looking for the feature to delete houses while ingame. would it be possible to add a /deletenearbyhouse to delete whichever house you last entered.

**Comment by Boom1053** [comment]
> 

monkey did u ever finish this?

**Comment by MattiLarson** [comment]
What if you accidently add houses on the wrong tier? How do you remove them as  now have two houses in the same spot
