### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kokorog** [qbcore-framework/qb-houses#127]
![image](https://user-images.githubusercontent.com/47898925/148945820-67841fd3-2258-4f00-abce-7657873eb1f5.png)

**Comment by amineohn** [comment]
lol, that's just an little thing with " integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"" that's not a really a bug.
