### ISSUE TITLE
[BUG] - Some items not staying at the Z coords you placed it on.

### ISSUE THREAD

**Issue by Duguayster** [qbcore-framework/qb-houses#144]
**Describe the bug**
There are some objects that will not stay in the place you've placed it at, like for example, you place a TV on the ground, and when you buy it, it shoots to the ceiling... I've placed a tower fan on the floor and when you buy it an confirm its location, it shoots up to about knee height.

**To Reproduce**
1. Go to decorate within a house, and place a tv or tower fan
2. You will see the object will not stay in place and shoot up
3. No errors in console.

**Expected behavior**
When you place one of the two objects mentioned you will see it will not stay in the place intended.

**Screenshots**
https://media.discordapp.net/attachments/782154978701606932/934952255394824202/QBCore_-_Furniturenotsitting_right.png?width=1202&height=676

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] - Updated qb-core & qb-houses today
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] No custom resource for housing
 - Have you renamed `qb-` to something custom? [e.g. yes/no] did not rename any resource

**Additional context**
Nope just plain and simple, some objects not being placed as intended.

**Comment by Branqueador** [comment]
I have the same issue

**Comment by Klay4** [comment]
+1

**Comment by PlanovskyJus** [comment]
This continues to be an issue
