### ISSUE TITLE
[BUG] Can't leave the decoration menu after buying something

### ISSUE THREAD

**Issue by Klay4** [qbcore-framework/qb-houses#146]
**Describe the bug**
If I buy a prop and then try to leave the ui I can't, but if I don't buy nothing I can close the ui by pressing ESC.

**To Reproduce**
1. Opened the decoration menu with the F1 menu
2. Selected a chair and placed it
3. Bought the chair prop
4. Recived the bank notification for the purchase
5. Can't leave the ui by clicking ESC or BACKSPACE (I need to restart the game)

(I'm using the last version of qb-houses)

**Screenshots**
No errors on client/server side
![20220125141338_1](https://user-images.githubusercontent.com/39599216/150983441-6b9c8d09-d1ce-4314-98fd-77a95361003b.jpg)

**Comment by Patrickstek121** [comment]
On line 265 of decorate.lua fixed this issue to replace SetNuiFocus(false, false) to
SetNuiFocus(true, true)

**Comment by Klay4** [comment]
@Patrickstek121 thenk you very much, working!
