### ISSUE TITLE
[BUG] The house contract doesn't go away

### ISSUE THREAD

**Issue by Klay4** [qbcore-framework/qb-houses#148]
if you press ESC when you have the house contract open, the ui of the contract remains on screen until you restart fivem.

**Comment by vosscat** [comment]
same

**Comment by Baelroak** [comment]
I fixed this issue by adding the code inside the square from the image below, it was causing other issues like being able to buy a house already owned etc so this fixes that too.

![ezfix](https://user-images.githubusercontent.com/68571188/159114632-e666a980-ba60-4192-95fa-590392e97708.png)

**Comment by Baelroak** [comment]
> if you press ESC when you have the house contract open, the ui of the contract remains on screen until you restart fivem.

> same

I fixed this issue by adding the code inside the square from the image below, it was causing other issues like being able to buy a house already owned etc so this fixes that too.

![ezfix](https://user-images.githubusercontent.com/68571188/159114632-e666a980-ba60-4192-95fa-590392e97708.png)
