### ISSUE TITLE
[BUG] Sold houses are enterable by realestate job holders

### ISSUE THREAD

**Issue by itismejoey** [qbcore-framework/qb-houses#155]
**Describe the bug**
When working as the `realestate` job, after a house is sold it still allows you to enter the house. 

**To Reproduce**
1. Put a house on the market
2. Have someone purchase the house
3. Go up to the door as a `realestate` person and you'll have the same options to enter the house as if you owned it

**Expected behavior**
Ideally once the house is sold no one, except the house owner or those with keys, should be able to enter the house.

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] 7 hours ago (latest files)
 - Are you using custom resource? which ones? None that should effect this
 - Have you renamed `qb-` to something custom? No.

**Comment by itismejoey** [comment]
Not sure why this was closed, as it's still an issue.

**Comment by iktray** [comment]
@GhzGarage Reopen issue.

**Comment by GhzGarage** [comment]
> @GhzGarage Reopen issue.

This is not an issue, this is how it works

**Comment by itismejoey** [comment]
Then I’d suggest changing it to be an enhancement/update. It’s just very strange that a real estate person can go into a house after it’s sold.
