### ISSUE TITLE
[BUG] Freeze UI

### ISSUE THREAD

**Issue by nemaDev** [qbcore-framework/qb-houses#163]
any solution on the problem of being stuck in the house decoration UI? It freezes and no keys work. ESC, F5, etc

**Comment by BerkieBb** [comment]
Hold F5

**Comment by nemaDev** [comment]
nothing happens. I'm still frozen
![image](https://user-images.githubusercontent.com/28969108/159080783-7cef1def-baf8-48ef-9329-15d686e7989f.png)

**Comment by BerkieBb** [comment]
When holding F5 you get your mouse, try pressing F5 and then holding F5 to get your mouse

**Comment by nemaDev** [comment]
nope, it doesn't work for me

**Comment by NightRider18133** [comment]
Im having this issue as well works great for the first item then it freezes and throws a f8 error on the newest version you have to f8 out also is there any way to fix the UI for the command menu you cant read it
