### ISSUE TITLE
[BUG] Cant access menu

### ISSUE THREAD

**Issue by GhostLegionRP** [qbcore-framework/qb-houses#166]
![DrawText_error](https://user-images.githubusercontent.com/100316482/160709781-4f2299a8-218e-4438-9911-f09328934ebb.PNG)

**Comment by purplecofe** [comment]
> ![DrawText_error](https://user-images.githubusercontent.com/100316482/160709781-4f2299a8-218e-4438-9911-f09328934ebb.PNG)

You need latest QBCore version
