### ISSUE TITLE
Cant remove someone's keys to a house 

### ISSUE THREAD

**Issue by Themaddness** [qbcore-framework/qb-houses#170]
When I try to remove someone's keys on the radial menu it doesn't remove the keys and there are no errors as well.

**Comment by Themaddness** [comment]
It doesn't remove them on the DB either

**Comment by Rav3n95** [comment]
@GhzGarage Found the issue, if you want i can pr it.

**Comment by erikmeyer08** [comment]
Is there a fix for this?
Seems like allot of things are broken in this script now since the latest qbcore updates have been pushed.

**Comment by ZonixZA** [comment]
Hi guys has that PR been posted to resolve this issue

**Comment by nzkfc** [comment]
Just found this PR due to a player reporting this issue. Thanks for your work on the fix @Rav3n95, hopefully we can get that PR into production along with the streetcount and exit menu PR that are there.

**Comment by galibmahin** [comment]
Any one fixed the issue?
