### ISSUE TITLE
[BUG] Object On The Ground

### ISSUE THREAD

**Issue by CxCore-xyz** [qbcore-framework/qb-houses#194]
**When you enter the decorate mode and decorate everything on the ground after you exit everythings above the floor like 1meter. Tried alot of thing to make it work but unfortnatly the object always floats in the air :(**

**Comment by GhzGarage** [comment]
Try this https://github.com/qbcore-framework/qb-houses/commit/ffd56d51f5724afa29456d494c69f107957fd02c
