### ISSUE TITLE
[BUG]  attempt to index a nil value (field '?')

### ISSUE THREAD

**Issue by k0ngzz** [qbcore-framework/qb-houses#195]
Hi, when I do the /getoffsets command I get an error saying:

script:qb-houses  SCRIPT ERROR: @qb-houses/client/main.lua1553:  attempt to index a nil value (field '?')
script:qb-houses  > ref (@qb-houses/client/main.lua:1553
script:qb-houses  > callback (@chat/client/cl_chat.lua:108)

I have not touched anything in qb-houses and it the first time I'm trying this command.

![error](https://user-images.githubusercontent.com/107633847/180654408-4c1554b5-963c-4b5c-82ab-4129bac05c1a.png)

**Comment by GhzGarage** [comment]
Couldn't replicate this
