### ISSUE TITLE
Many bugs

### ISSUE THREAD

**Issue by Rzoned** [qbcore-framework/qb-houses#20]
-if you try and decorate your house you get stuck in the decoration menu

-if you logout inside of a house it doesnt seem to know where to put you and you get an infinate loading screen 

-realestate agents cant buy a house themself so if they want to buy a house for themself they need to be fired buy the house then get rehired

**Comment by ihyajb** [comment]
The only issue I found is "realestate agents cant buy a house themself so if they want to buy a house for themself they need to be fired buy the house then get rehired"

if you get a loading screen forever when logging out its because you may have restarted a script qb-houses depends on.
