### ISSUE TITLE
[SUGGESTIONS] lots of suggestions

### ISSUE THREAD

**Issue by TonybynMp4** [qbcore-framework/qb-houses#201]
Bringing it here i guess @GhzGarage  :p

# Base ideas:

- Use the base gta online interiors (apartments, offices, garages, etc and the add ons like K4mb1's empty interiors etc to have more options
    -  Maybe use IPLs (I know it's definitely possible somehow ESX did it lol)?
- Add a marker to see where properties are more easily (shouldn't cauz too much performance loss.. right?)
- Replace the current garage system by the same system as apartments, with garage interiors kinda like GTA:Online with a **capacity** for each garage (instead of somehow stocking infinite amounts of cars on the same 5ft of concrete) to be a bit more **realistic** and create a system of garage **tiers** (2,6,10,12,20 etc... Slots) 
- Add offices for jobs (i.e lawyer or real estate) to have a real office	
- Add a rent system where you can rent an property for x amount of time for a certain price (i.e 2k$ a week for a 10 slots garage) renewable (ofc)
- Make the real estate agents actually useful by making them necessary to:
     - Renew rents, 
     - Buy properties, 
     - Let them modify properties that aren't bought/rented, 
     - If the property IS bought or rented, don't apply the modifications but send a mail to the owner and if he accepts (using the checkmark button) he pays for the modifications and it applies them
- Remove the commands and replace them by the radial menu
- Have the slots for garages in the config (or a separate config file) 
   - (like for x interior you have y slots and the cars appear at *list of offset coordinates*)
- Instead of opening the property's menu directly, open a list of the properties, allowing for multi-floor properties (imagine multiple apartments on the same building for example)
  - Only if the property has multiple propetries ofc

## Decorations menu:

- An All category which just lets you search within the entirety of the props (with like a search bar and then a list of all the results) 	
- The normal categories we have now
- A better and simpler UI (the current one feels a bit weird imo)
- The possibility of sharing the 'interior' somehow ? (Not really sure 'bout that one tbh)

## Property creation menu:

- Open a qb-menu with the name of the 'property' as a header, a button "add a property" and a close button
When selected it opens a qb-input with the following options:
    - Is a garage ?
         - Checkbox that if selected changes the options possible in the next option to garages
    - Tier 
         - A list with either garages if the previous box is checked or apartments/offices
    - Storage capacity
         - A number input to change the max capacity of the stash
         - Configurable tax (i.e weight*tax so 500kg*2=1000$)
         - Disabled if it's a garage 
    - Has a pool ? 
         - Checkbox that if selected adds a certain tax (configurable) to the price 
         - Disabled if it's a garage 
    - Has a garden ?
         - Same as the pool with configurable tax
         - Disabled if it's a garage 
    - Can't be rented ?
         - If selected remove the possibility to rent 
         - Disabled if it's a garage 
    - Confirm button 

### For real estate agents :
- Name of the property
- Property list
  - If bought:
      - Name of the property (like 10th alta street a for example)
      - Ring/knock 
          - Sends a notification to the owners that someone's at the door
          - If no owners are connected notifys the person that no one's home
      - Modify
          - Either
             - Opens the creation input but prefilled with the properties options
          - Or
             - opens a list with the property's infos  that if clicked, lets you change the selected info
      - Done button
          - Sends an invoice to the owner and if accepted applies the modifications and give 10% of the price of each modifications to the agent (let's say you change the capacity of the stash it costs 2k$ and the agent receives 200$)
  - If rented:
      - Same as bought but with an "extend rent" button
          - Sends a mail to the owner and if he clicks the checkmark he pays for a week and it extends the rent
  - If it's neither of the above
      - Name of the property
      - Sell
          - Opens an input with:
              - Player ID
              - Commission the agent will add to the final price and receive (so agents can take different % and be more/less competitive)
                 - with a configureable min - max ofc
              - Done
                 - Sends invoice to the player ID
      - Rent
          - Opens input with:
              - Player ID
              - Number of weeks to rent the property for
              - Done
                 - Sends invoice to the player ID 
      - Back
- Close
		
### For the others :
- Name of the property 
- Property list
  - Name of the property (ex 10th Alta street a)
    - If it's bought/rented
      - Knock/ring
    - If it's available for purchase/rent
      - Visit
        - Lets you enter the property to visit it
    - If the property is your's and it's rented add the end of the rent date
  - Back
- Close

## In the garage:
	
- Have a marker that opens the list of the cars stored in the garage
  - When a car is selected it spawns you in the car outside the garage 
    - Prevent the possibility of cars being invisible and therefore impossible to get out of the garage 
- Cars visible like in GTA:O

## In the apartments:

- Same as currently with better decorations menu

like i said.. lots of suggestions 😅

**Comment by TonybynMp4** [comment]
@GhzGarage  should i move this issue to the new repo ?

**Comment by GhzGarage** [comment]
> @GhzGarage should i move this issue to the new repo ?

Go ahead
