### ISSUE TITLE
[BUG] remove key from player

### ISSUE THREAD

**Issue by guymalul** [qbcore-framework/qb-houses#212]
annot remove house key

**To Reproduce**
1. Go to 'radial,'
2. Click on 'remove house key'
3. no error comes up in console or client console

**Expected behavior**
i give house key to one of my frind and i try to remove i see the name but after i click the name its not remove any key and my frind can enter the house.
and if i try to remove again the name of my frind pop up again

![image](https://user-images.githubusercontent.com/113706765/190672361-1ec35057-c40d-4f4c-aabe-6b2829ef77c9.png)

 - last week
 - nope
 - nope

**Comment by Joelelfstrom** [comment]
Same issue

**Comment by Kingston166** [comment]
Is there a Fix to this im having the same issue
