### ISSUE TITLE
[BUG] Decorating Bugged

### ISSUE THREAD

**Issue by Fear6682** [qbcore-framework/qb-houses#213]
**Describe the bug**
Whenever Someone does /decorate or goes onto decorate with the F1 menu they cant move or interact with anything other than what you can click with your mouse (objects, close and my objects).
**To Reproduce**
We use an older version but when I download the Newer version there's loads of errors and none of the houses work.
I Have provided the error for the NEW version in an image. There is not console or F8 error for the old versions.

I expect the decorating feature to work and for the players to be able to move around

 - New Version doesn't work and old version has decorating bug
 - Many custom resources (~350)
 - All QB Scripts still keep the same name without the -main or -master at the end of the folder

![QB Houses error](https://user-images.githubusercontent.com/113636227/191301240-8237023d-6441-41d2-9fcb-8b3bcff3773a.PNG)

**Comment by Hitmydabs** [comment]
I have this issue as well with this system

**Comment by Fear6682** [comment]
i made the house as a realestate agent then bought it myself, would it still work?
