### ISSUE TITLE
[BUG] Flying car

### ISSUE THREAD

**Issue by Ivofy** [qbcore-framework/qb-houses#217]
Hello!

If u leave your apartments/house and sit in your vehicle it start flying ( doing some circles )
https://medal.tv/games/gta-v/clips/E265CmRaOF0-D/d1337fCuEPN1?invite=cr-MSxRbEEsMTI2MDY4NDAzLA

**Comment by nzkfc** [comment]
That is a prop collision issue, generally it has to do with a resource that features a custom prop or putting a prop onto the body, kinda like your gun on the hip.

If you do /refreshskin or whatever your clothing refresh is, the car will stop flipping out.
