### ISSUE TITLE
[BUG] cant decorate houses

### ISSUE THREAD

**Issue by Krisb239** [qbcore-framework/qb-houses#224]
**Describe the bug**
When trying to decorate the house the controls dont work. You can select furniture but cant do anything with it. This is from a fresh install. Stashes also dont work. I can place them and open them but i cant store anything inside.

**To Reproduce**
go inside house and try to decorate

**Expected behavior**
place items and use controls as intended

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: fresh install
 - Are you using custom resource? which ones? a lot
 - Have you renamed `qb-` to something custom? no

**Additional context**

**Comment by 6utzeit** [comment]
Same for me.

**Comment by mertayv** [comment]
same here ...
