### ISSUE TITLE
[BUG]  i updated my qb-houses but afterwards since when i add garages to the houses after a restart of the server the garage blips no longer appear the houses work fine but the garages no longer work

### ISSUE THREAD

**Issue by RevelationStudiosGaming** [qbcore-framework/qb-houses#225]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**

**Comment by floyd75** [comment]
Same here. After a restart, the marker is gone. The state of the stored vehicle in the Database is 1.  When your job is realestate and you add the garage again, the vehicle is still in the garage and after /addgarage you can pull it out. :)

**Comment by joshinator-Josh** [comment]
> Same here. After a restart, the marker is gone. The state of the stored vehicle in the Database is 1. When your job is realestate and you add the garage again, the vehicle is still in the garage and after /addgarage you can pull it out. :)

yeah but its rediculous that we have to readd the garage everytime we restart

**Comment by didis97** [comment]
same here

**Comment by theogfromheaven** [comment]
same here

**Comment by theogfromheaven** [comment]
There's a fix in the qb garages. Check it out
