### ISSUE TITLE
[BUG] Performance Issues

### ISSUE THREAD

**Issue by erikmeyer08** [qbcore-framework/qb-houses#231]
Does anybody else have performance issues with this script? I have severe frame loss in my server and when I run the profiler, the issue points to the qb-houses script as the script seems to load all the PolyZones as you move around the map. I run a large city with a ton of houses so I get that reducing the number of houses would help but its hard for me to tell some players they can have a house sand others that they are not aloud. Can this resource be reworked so that it doesn't load all these PolyZones like this at once?

![image](https://user-images.githubusercontent.com/43043270/219672909-6d4ed88f-c774-4e6b-8b3e-00c0f8e81acc.png)

**Comment by erikmeyer08** [comment]
@nzkfc Are you using something like Loaf housing now or stuck with this resource?

**Comment by nzkfc** [comment]
Loaf won't reply to some pre-purchase questions, seems they are also not
really replying in their discord either apart from some support staff.

I heard two groups are making a housing script, which is project sloth and
the other I think zoo is making, not sure on details
