### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LHRPOwner** [qbcore-framework/qb-houses#235]
I'm new to qbcore I've tried to make houses and it worked at first but now this is happening 
![image](https://github.com/qbcore-framework/qb-houses/assets/137975230/a3bebb2b-f7e8-4c3b-9c36-59f9c18c5ab8)
can someone help!!

**Comment by rodrigoandrade1** [comment]
As the message says, the qb-clothing resource is a dependency, did you put it in the resources folder?
