### ISSUE TITLE
Decorating Issue

### ISSUE THREAD

**Issue by two2one1nine9** [qbcore-framework/qb-houses#236]
When i decorate my house, I cant move the item. I can move it up and down and tilt it but i can not move it to a new location in my house. It says to left click with the red line on the item and hold the click and drag it but it doesnt move. Help. Ive been struggling with this for a month. Other people on my server say they can do it but for some reason, i cant. I have disconnected all keybinds but still nothing. Can someone help me with this please?

**Comment by NianticHack** [comment]
admin pemalas bila ntah nak fix kan
