### ISSUE TITLE
add Notify

### ISSUE THREAD

**Issue by evanillaa** [qbcore-framework/qb-houses#26]
The employee should not be allowed
example
/createhouse 1 100
This is allowed
If the number is more than 7
The message should not be allowed

    if Config.Houses[house].tier == 1 then
        data = exports['qb-interior']:CreateTier1House(coords)
    elseif Config.Houses[house].tier == 2 then
        data = exports['qb-interior']:CreateTrevorsShell(coords)
    elseif Config.Houses[house].tier == 3 then
        data = exports['qb-interior']:CreateMichaelShell(coords)
    elseif Config.Houses[house].tier == 4 then
        data = exports['qb-interior']:CreateApartmentShell(coords)
    elseif Config.Houses[house].tier == 5 then
        data = exports['qb-interior']:CreateCaravanShell(coords)
    elseif Config.Houses[house].tier == 6 then
        data = exports['qb-interior']:CreateFranklinShell(coords)
    elseif Config.Houses[house].tier == 7 then
        data = exports['qb-interior']:CreateFranklinAuntShell(coords)
    end

**Comment by fbagjug** [comment]
#27 will add this
