### ISSUE TITLE
Enter owned house error

### ISSUE THREAD

**Issue by OutragedMetro** [qbcore-framework/qb-houses#45]
I am trying to enter a owned house on my server but everyone gets the following error on there client side no server error's  is this a bug or?

`Script Error @qb-houses/client/main.lua:573 attempt to index a nil value (upvalue 'data)
Handler (@qb-houses/client/main.lua:53)`

**Comment by OutragedMetro** [comment]
Anyone?

**Comment by Hiperinio** [comment]
Same issue, with a fresh installed version.
After you create a house, you decorate it. Log out and restart server, then you'll get this error when you want to go inside the house.
