### ISSUE TITLE
add more function

### ISSUE THREAD

**Issue by darknight2590** [qbcore-framework/qb-houses#49]
I hope there is a function for each of the following scripts:
house function haskey = returns the value of true or false
vehilcekey function haskey = returns the value of true or false
qb-inv function haveitem = returns the value of true or false
return exports["qb-house"]:isNearHouse(true)
return exports["qb-house"]:HaveKey(true)
return exports["qb-vehilcekey"]:HaveKey(true)
exports["qb-inventory"]:haveitem("lockick", 1,)
It is easy to use other projects
I hope to see this in qbcore

**Comment by hoodz123** [comment]
do you have a working scripts buddy @darknight2590
