### ISSUE TITLE
[BUG] qb-housing /enter randomly stops working after a restart

### ISSUE THREAD

**Issue by legende11** [qbcore-framework/qb-houses#51]
**Describe the bug**
You can't enter your house anymore after a restart.

**To Reproduce**
1. create a house and sell it to the player
2. restart the server a few times

**Expected behavior**
You should see a /enter 3dtext and typing /enter teleports you into the house

**last update** 
 - I have updated last week

**Comment by GhzGarage** [comment]
Could you try updating now?

**Comment by legende11** [comment]
the 3d text shows up now, upon /enter i get the error

```
SCRIPT ERROR: @qb-houses/client/main.lua:412: attempt to index a nil value (upvalue 'data')
```

**Comment by GhzGarage** [comment]
In your database for the house locations table, you can see “tier” is set as “tinyint”. Change that to “smallint”

**Comment by legende11** [comment]
that fixed it. thanks @GhzGarage
