### ISSUE TITLE
[BUG] houses and radialmenu glitch

### ISSUE THREAD

**Issue by RadhwaneDZ** [qbcore-framework/qb-houses#55]
**Describe the bug**
glitch on qb-houses and radialmenu its need 3 people 
person A have a house 
person B & C doesnt have any house , if they know the exact place of the person A house they go to A house door , so B open radialmenu>general>House Interaction>givehousekey and click  the same process C do the same steps so the result is a /enter will appear immediately for both person B & C 

so this glitch only work if you know the exact house of any person 
you can check the video 
https://www.youtube.com/watch?v=GX5tGFQ9TTE

**To Reproduce**
1. Go to 'radialmenu>general>House Interaction>givehousekey' 2 person must do this for each when stand on person A house
2. givekey to nearby player ( must dont have any house bought from realestate for both 
3.  /enter will appear for both players and can enter a house of other player 

**Expected behavior**
if person B & C doesnt have a house so if they open radialmenu , givehousekeys should not be appear , also if they bought a house they cannot make this glitch 
if its possible on every house bought to a player should generate key like citizenID so only this key can open that house  

**Screenshots**
https://www.youtube.com/watch?v=GX5tGFQ9TTE

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] **zdiscord , battlepass ( already sent u invite to convert it for me , berkieb already participate on that battlepass script , waveshield anticheat** 
 - Have you renamed `qb-` to something custom? [e.g. yes/no] **NO**

**Additional context**
no

**Comment by leoyassir** [comment]
same issues
from house owner : https://streamable.com/twmapj
from me : https://streamable.com/9uetsi
