### ISSUE TITLE
[BUG] Can't see other players houses

### ISSUE THREAD

**Issue by Hiperinio** [qbcore-framework/qb-houses#61]
**Describe the bug**
When someone else buys a house, other players can't see the house. They can't see the text of the house so they can't ring the bell etc.

**To Reproduce**
1. Someone buys an house
2. Go to their house door, you can't see it.

**Expected behavior**
To see the house text so you can ring the bell on it.

**Screenshots**
https://gyazo.com/df1d6574919fa3dfe5c8d6895b8c2b49 - as the player who bought the house / realestate
https://gyazo.com/f5486d7d6e04c0edd350a2da29e239a7 - as a normal player

**Questions (please complete the following information):**
 - When you last updated: today
 - Are you using custom resource? which ones? no
 - Have you renamed `qb-` to something custom? no

**Comment by roobr** [comment]
Please try relog and see if it fixes it, or go /logout.

Also try and see if the realestate agent makes a house when you are standing there if the message appears or not.
