### ISSUE TITLE
[SUGGESTION] IPL support

### ISSUE THREAD

**Issue by EvilGnome93** [qbcore-framework/qb-houses#71]
**Is your feature request related to a problem? Please describe.**
IPL's not supported

**Describe the feature you'd like**
It would be awsome if the script would support ipl houses

**Describe alternatives you've considered**
There is none for this althrough there is a ESX paid script for it.

**Comment by BlueSky-fur** [comment]
Any update on this?

**Comment by WEEZOOKARP** [comment]
chances are this wont happen because interior shells seem to be the way the devs are heading in order to be able to get some money out of this.

**Comment by BlueSky-fur** [comment]
> chances are this wont happen because interior shells seem to be the way the devs are heading in order to be able to get some money out of this.

I dont really understand, in what way are they gonna make money of this?

**Comment by WEEZOOKARP** [comment]
Check qb interiors optional.lua at the top and notice there is a telex link
