### ISSUE TITLE
[BUG] Furniture inside of house vanishing and reappearing

### ISSUE THREAD

**Issue by DynOBear** [qbcore-framework/qb-houses#92]
Describe the bug
When inside of an interior, furniture placed below my characters waste vanish and reappear as I move my third person camera. Certain x y z coordinates are below of where its happening. My thought is that you can move the interior up and fix it but I don't know what that would do to everything else like furniture or other players housing.

To Reproduce

Go to '(X: -1126.36) (Y: 382.59) (Z: 50 to 40)'
Crate the Franklins house interior
Place items that are below the waist of the character that are located on the floor on the black surface of the main story.
Items glitch and appear and disappear while moving you third person cameras around.
Screenshots

Questions (please complete the following information):
-Will the interior furniture move with the interior or stay planed when the interior is moved up or down.
-What other things may be affected by fixing this issue

Additional context
I am not the server owner or a Dev, 
I am simply a player who is trying to find a solution to the issue. Excuse my possible ignorance on the topic i am doing as much research as I can to solve the issue.

![VanishingFurniture1](https://user-images.githubusercontent.com/95674749/145311102-9d01df2e-3b1d-4019-90ac-deec10af2e60.jpg)

![VanishingFurniture2](https://user-images.githubusercontent.com/95674749/145311104-e6a89207-5b4b-4f8f-9c25-e9245c67773f.jpg)

**Comment by IdrisDose** [comment]
Thank you for this in-depth report, we'll look into this and see if it can be resolved :)
