### ISSUE TITLE
[BUG] Police not able to stormram doors

### ISSUE THREAD

**Issue by ansljeremy** [qbcore-framework/qb-houses#94]
**Describe the bug**
Police can't stormram a door down after the swap to qb-menu.

**To Reproduce**
1. Go to an owned house
2. Use stormram

**Expected behavior**
Ability to enter the house

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] Most recent (12 days ago)
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] Many, none would interfere with this
 - Have you renamed `qb-` to something custom? [e.g. yes/no] No

**Comment by BlueSky-fur** [comment]
can confirm, we have the same issue.

**Comment by killzone185** [comment]
Confirm we have the same issue

**Comment by BlueSky-fur** [comment]
tested it on a completly clean, unmodified install of QBCore issue occurs there too.

**Comment by IdrisDose** [comment]
Hey all, did this occur after the menu update? cb68405d8beabd23f95c561f00cb8d680d298713

**Comment by killzone185** [comment]
I don’t think it ever worked

**Comment by RoyLTea** [comment]
Updated to the latest version and still not working. I also noticed that if the ram is used and the server restarts before you can relock the door then when it comes back up everyone can enter every house regardless.

**Comment by killzone185** [comment]
Never knew that

**Comment by IdrisDose** [comment]
Alrighty I'll have to investigate these issues post-christmas and I'll tag this issue when fixing.

**Comment by killzone185** [comment]
Appreciate that

**Comment by kevintransp** [comment]
Has anyone the solution to let the stormram work?
